sudo: false
language: node_js
env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  artifacts:
    s3_region: us-east-1
    paths:
      - $(git ls-files -o screenshots/ | tr "\n" ":")

before_install:
  - npm install -g npm@5.2.0  # Do not bump until https://github.com/npm/npm/issues/17858 is fixed

script:
  - npm run lint
  - ./travis-testcafe.sh

after_success:
  - tools/docker-build.sh
