// Auth Actions
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR';
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'


// Admin Actions
export const GET_CHANGE_REQUESTS = 'GET_CHANGE_REQUESTS';
export const GET_CHANGE_REQUESTS_SUCCESS = 'GET_CHANGE_REQUESTS_SUCCESS';
export const GET_CHANGE_REQUESTS_FAILURE = 'GET_CHANGE_REQUESTS_FAILURE';
export const GET_PENDING_SERVICES = 'GET_PENDING_SERVICES';
export const GET_PENDING_SERVICES_SUCCESS = 'GET_PENDING_SERVICES_SUCCESS';
export const GET_PENDING_SERVICES_FAILURE = 'GET_PENDING_SERVICES_FAILURE';
export const APPROVE_CHANGE_REQUEST = 'APPROVE_CHANGE_REQUEST';
export const APPROVE_CHANGE_REQUEST_SUCCESS = 'APPROVE_CHANGE_REQUEST_SUCCESS';
export const APPROVE_CHANGE_REQUEST_FAILURE = 'APPROVE_CHANGE_REQUEST_FAILURE';
export const DENY_CHANGE_REQUEST = 'DENY_CHANGE_REQUEST';
export const DENY_CHANGE_REQUEST_SUCCESS = 'DENY_CHANGE_REQUEST_SUCCESS';
export const DENY_CHANGE_REQUEST_FAILURE = 'DENY_CHANGE_REQUEST_FAILURE';
export const APPROVE_PENDING_SERVICE = 'APPROVE_PENDING_SERVICE';
export const APPROVE_PENDING_SERVICE_SUCCESS = 'APPROVE_PENDING_SERVICE_SUCCESS';
export const APPROVE_PENDING_SERVICE_FAILURE = 'APPROVE_PENDING_SERVICE_FAILURE';
export const DENY_PENDING_SERVICE = 'DENY_PENDING_SERVICE';
export const DENY_PENDING_SERVICE_SUCCESS = 'DENY_PENDING_SERVICE_SUCCESS';
export const DENY_PENDING_SERVICE_FAILURE = 'DENY_PENDING_SERVICE_FAILURE';